# Generated by Django 6.0.1 on 2026-01-14 07:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('author', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='blogimages')),
                ('date_created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
