# Generated by Django 6.0.1 on 2026-01-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='blogimages/avatar'),
        ),
    ]
