# Generated by Django 6.0.1 on 2026-01-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_blog_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='blogs/avatar'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, upload_to='blogs/images'),
        ),
    ]
