# Generated by Django 6.0.1 on 2026-01-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_blog_avatar_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='avatar',
            field=models.ImageField(default='defaults/avatar.png', upload_to='blogimages'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, upload_to='blogimages'),
        ),
    ]
