# Generated by Django 6.0.1 on 2026-01-26 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='number',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Phone number must start with +977 and contain exactly 10 digits after it.', regex='^\\+977\\d{10}$')]),
        ),
    ]
