# Generated by Django 6.0.1 on 2026-01-28 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_internship'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='read_time',
            field=models.DurationField(default=datetime.timedelta(seconds=480)),
        ),
    ]
