# Generated by Django 6.0.1 on 2026-01-29 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_blog_read_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='avatar',
        ),
    ]
