# Generated by Django 6.0.1 on 2026-01-29 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_blog_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='number',
            new_name='phone',
        ),
    ]
