# Generated by Django 6.0.1 on 2026-01-29 17:13

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_number_contactmessage_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=20)),
                ('college_name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must start with +977 and contain exactly 10 digits(e.g., +977 98XXXXXXXX) after it.', regex='^\\+977\\s?\\d{10}$')])),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('internship_title', models.CharField(max_length=100)),
                ('cv_file', models.FileField(upload_to='cvs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), api.models.validate_file_size])),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
