# Generated by Django 6.0.1 on 2026-01-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_internshipapplication'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='internshipapplication',
            constraint=models.UniqueConstraint(fields=('email', 'internship_title'), name='unique_application_per_email'),
        ),
    ]
