# Generated by Django 6.0.1 on 2026-01-30 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_internshipapplication_unique_application_per_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='internshipapplication',
            name='unique_application_per_email',
        ),
        migrations.AddField(
            model_name='internship',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='internship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.internship'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('reviewing', 'Reviewing'), ('interview', 'Interview'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='internshipapplication',
            constraint=models.UniqueConstraint(fields=('email', 'internship'), name='unique_application_per_email'),
        ),
        migrations.RemoveField(
            model_name='internshipapplication',
            name='internship_title',
        ),
    ]
