# Generated by Django 6.0.1 on 2026-01-30 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_internshipapplication_unique_application_per_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipapplication',
            name='internship',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.internship'),
            preserve_default=False,
        ),
    ]
